# Generated by Django 5.2.7 on 2025-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrequest',
            name='service_type',
            field=models.CharField(choices=[('shirt_ironing', 'Shirt Ironing'), ('trousers_ironing', 'Trousers Ironing'), ('full_ironing', 'Full Ironing Service'), ('suits', 'Suit Cleaning & Pressing'), ('full_home_service', 'Full Home Service'), ('wash_dry', 'Wash & Dry'), ('hand_wash', 'Hand Wash'), ('dry_clean', 'Dry Clean'), ('special_care', 'Special Care (Delicates)'), ('other', 'Other')], default='full_home_service', max_length=30),
        ),
    ]
