# Generated by assistant: create PricingItem model migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_laundryrequest_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=10, blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ['ordering', 'slug']},
        ),
    ]
